#!/bin/bash
#
# pkg-config wrapper for PARM sb2 cross-build
# Mehmet Emre Atasever
#
# copy this script into toolchain directory and add bin directory of
# the toolchain at the first of PATH variable
#
# if $SYSROOT variable exported by cross-build, this script adds $SYSROOT
# to the flags
#
# Example output:
#
# $ cp pkg-config /var/cross/sysroots/armv7l/bin
# $ PATH=/var/cross/sysroots/armv7l/bin:$PATH
# $ which pkg-config
# /opt/toolchain/armv7l/bin/pkg-config
# $ pango > pkg-config --cflags --libs xrender
# -lXrender -lX11
# $ SYSROOT=/var/cross/sysroots/armv7l pkg-config --cflags --libs xrender
# -I/var/cross/sysroots/armv7l/usr/include  -L/var/cross/sysroots/armv7l/usr/lib -lXrender -lX11
#

args=
requires_cross_fix=false

while [ x"$1" != x"" ]; do
    args="${args} $1"

    case "$1" in
        --cflags*|--libs*|--variable*)
            requires_cross_fix=true
            ;;
    esac
    shift
done

${requires_cross_fix} && {
    if ! [ -z "$SYSROOT" ]; then
        args="${args} --define-variable=prefix=${SYSROOT}/usr --define-variable=exec_prefix=${SYSROOT}/usr"
    fi
}

# echo "args= \"$args\""
exec /usr/bin/pkg-config $args

