#!/usr/bin/python
# -*- coding: utf-8 -*-

# Python Core Libraries
import sys

# PyQt4 Core Libraries
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import QCoreApplication

# Rasta Core Library
from rastaLib import Rasta
from rastaLib import __version__

if __name__ == "__main__":
    app = QApplication(sys.argv)

    # Application Settings
    QCoreApplication.setOrganizationName("Pardus")
    QCoreApplication.setOrganizationDomain("pt.pardus.org.tr")
    QCoreApplication.setApplicationName("Rasta")
    QCoreApplication.setApplicationVersion(__version__)

    arguments = QCoreApplication.arguments()
    if len(arguments)>1:
        if arguments[1] == "--help":
            print "Usage :"
            print " $ rasta [filename] [options]"
            print 
            print "Options :"
            print " --help          : Show this help"
            print " --hidesource    : Hide source window"
            sys.exit(0)

    RastaUI = Rasta(arguments)
    RastaUI.show()
    sys.exit(app.exec_())

