# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetConfiguration.ui'
#
# Created: Tue Jul 06 14:55:12 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_widgetConfiguration(object):
    def setupUi(self, widgetConfiguration):
        widgetConfiguration.setObjectName("widgetConfiguration")
        widgetConfiguration.resize(471, 207)
        widgetConfiguration.setWindowTitle("")
        self.gridLayout = QtGui.QGridLayout(widgetConfiguration)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblDrive = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDrive.sizePolicy().hasHeightForWidth())
        self.lblDrive.setSizePolicy(sizePolicy)
        self.lblDrive.setMinimumSize(QtCore.QSize(120, 0))
        self.lblDrive.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDrive.setObjectName("lblDrive")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblDrive)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboDrive = QtGui.QComboBox(widgetConfiguration)
        self.comboDrive.setObjectName("comboDrive")
        self.horizontalLayout.addWidget(self.comboDrive)
        self.lblDriveFreeSpace = QtGui.QLabel(widgetConfiguration)
        self.lblDriveFreeSpace.setObjectName("lblDriveFreeSpace")
        self.horizontalLayout.addWidget(self.lblDriveFreeSpace)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.lblInstallation = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInstallation.sizePolicy().hasHeightForWidth())
        self.lblInstallation.setSizePolicy(sizePolicy)
        self.lblInstallation.setMinimumSize(QtCore.QSize(120, 0))
        self.lblInstallation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblInstallation.setObjectName("lblInstallation")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblInstallation)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sizeSlider = QtGui.QSlider(widgetConfiguration)
        self.sizeSlider.setMinimumSize(QtCore.QSize(250, 0))
        self.sizeSlider.setSingleStep(1)
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setObjectName("sizeSlider")
        self.horizontalLayout_2.addWidget(self.sizeSlider)
        self.lblSize = QtGui.QLabel(widgetConfiguration)
        self.lblSize.setObjectName("lblSize")
        self.horizontalLayout_2.addWidget(self.lblSize)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.lblFree = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFree.sizePolicy().hasHeightForWidth())
        self.lblFree.setSizePolicy(sizePolicy)
        self.lblFree.setMinimumSize(QtCore.QSize(120, 0))
        self.lblFree.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFree.setObjectName("lblFree")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblFree)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbFreeSpace = QtGui.QProgressBar(widgetConfiguration)
        self.pbFreeSpace.setMinimumSize(QtCore.QSize(250, 0))
        self.pbFreeSpace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbFreeSpace.setProperty("value", 0)
        self.pbFreeSpace.setObjectName("pbFreeSpace")
        self.horizontalLayout_3.addWidget(self.pbFreeSpace)
        self.lblFreeLeft = QtGui.QLabel(widgetConfiguration)
        self.lblFreeLeft.setObjectName("lblFreeLeft")
        self.horizontalLayout_3.addWidget(self.lblFreeLeft)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.line = QtGui.QFrame(widgetConfiguration)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.line)
        self.lblUsername = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUsername.sizePolicy().hasHeightForWidth())
        self.lblUsername.setSizePolicy(sizePolicy)
        self.lblUsername.setMinimumSize(QtCore.QSize(120, 0))
        self.lblUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblUsername)
        self.txtUsername = QtGui.QLineEdit(widgetConfiguration)
        self.txtUsername.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtUsername)
        self.lblPassword = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPassword.sizePolicy().hasHeightForWidth())
        self.lblPassword.setSizePolicy(sizePolicy)
        self.lblPassword.setMinimumSize(QtCore.QSize(120, 0))
        self.lblPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtGui.QLineEdit(widgetConfiguration)
        self.txtPassword.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.LblRetypePassword = QtGui.QLabel(widgetConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LblRetypePassword.sizePolicy().hasHeightForWidth())
        self.LblRetypePassword.setSizePolicy(sizePolicy)
        self.LblRetypePassword.setMinimumSize(QtCore.QSize(120, 0))
        self.LblRetypePassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LblRetypePassword.setObjectName("LblRetypePassword")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.LblRetypePassword)
        self.txtRetypePassword = QtGui.QLineEdit(widgetConfiguration)
        self.txtRetypePassword.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtRetypePassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtRetypePassword.setObjectName("txtRetypePassword")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.txtRetypePassword)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(widgetConfiguration)
        QtCore.QMetaObject.connectSlotsByName(widgetConfiguration)

    def retranslateUi(self, widgetConfiguration):
        self.lblDrive.setText(QtGui.QApplication.translate("widgetConfiguration", "Installation Drive", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDriveFreeSpace.setText(QtGui.QApplication.translate("widgetConfiguration", "GB free", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInstallation.setText(QtGui.QApplication.translate("widgetConfiguration", "Installation Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSize.setText(QtGui.QApplication.translate("widgetConfiguration", " GB", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFree.setText(QtGui.QApplication.translate("widgetConfiguration", "After Installation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreeLeft.setText(QtGui.QApplication.translate("widgetConfiguration", "GB free", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setText(QtGui.QApplication.translate("widgetConfiguration", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("widgetConfiguration", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.LblRetypePassword.setText(QtGui.QApplication.translate("widgetConfiguration", "Retype Password ", None, QtGui.QApplication.UnicodeUTF8))

