# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetOptInternet.ui'
#
# Created: Tue Jul 06 15:09:04 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_widgetOptInternet(object):
    def setupUi(self, widgetOptInternet):
        widgetOptInternet.setObjectName("widgetOptInternet")
        widgetOptInternet.resize(458, 211)
        widgetOptInternet.setWindowTitle("")
        self.gridLayout_2 = QtGui.QGridLayout(widgetOptInternet)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblChoose = QtGui.QLabel(widgetOptInternet)
        self.lblChoose.setMinimumSize(QtCore.QSize(110, 0))
        self.lblChoose.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblChoose.setObjectName("lblChoose")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblChoose)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboVersion = QtGui.QComboBox(widgetOptInternet)
        self.comboVersion.setObjectName("comboVersion")
        self.horizontalLayout_2.addWidget(self.comboVersion)
        self.lblSize = QtGui.QLabel(widgetOptInternet)
        self.lblSize.setObjectName("lblSize")
        self.horizontalLayout_2.addWidget(self.lblSize)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.lblVersion = QtGui.QLabel(widgetOptInternet)
        self.lblVersion.setMinimumSize(QtCore.QSize(110, 0))
        self.lblVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblVersion)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnUpdate = QtGui.QPushButton(widgetOptInternet)
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_3.addWidget(self.btnUpdate)
        self.btnProxy1 = QtGui.QPushButton(widgetOptInternet)
        self.btnProxy1.setObjectName("btnProxy1")
        self.horizontalLayout_3.addWidget(self.btnProxy1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.mirrorLabel = QtGui.QLabel(widgetOptInternet)
        self.mirrorLabel.setMinimumSize(QtCore.QSize(110, 0))
        self.mirrorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mirrorLabel.setObjectName("mirrorLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.mirrorLabel)
        self.comboMirror = QtGui.QComboBox(widgetOptInternet)
        self.comboMirror.setObjectName("comboMirror")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboMirror)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.lblDescription = QtGui.QLabel(widgetOptInternet)
        self.lblDescription.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lblDescription.setWordWrap(True)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCheck = QtGui.QPushButton(widgetOptInternet)
        self.btnCheck.setObjectName("btnCheck")
        self.horizontalLayout.addWidget(self.btnCheck)
        self.btnProxy2 = QtGui.QPushButton(widgetOptInternet)
        self.btnProxy2.setObjectName("btnProxy2")
        self.horizontalLayout.addWidget(self.btnProxy2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label = QtGui.QLabel(widgetOptInternet)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(widgetOptInternet)
        QtCore.QMetaObject.connectSlotsByName(widgetOptInternet)

    def retranslateUi(self, widgetOptInternet):
        self.lblChoose.setText(QtGui.QApplication.translate("widgetOptInternet", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSize.setText(QtGui.QApplication.translate("widgetOptInternet", " MB", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVersion.setText(QtGui.QApplication.translate("widgetOptInternet", "Version List", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("widgetOptInternet", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProxy1.setText(QtGui.QApplication.translate("widgetOptInternet", "Set Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorLabel.setText(QtGui.QApplication.translate("widgetOptInternet", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescription.setText(QtGui.QApplication.translate("widgetOptInternet", "You are about to download Pardus using Internet connection. Make sure that you are connected to Internet.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheck.setText(QtGui.QApplication.translate("widgetOptInternet", "Check Compatibility", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProxy2.setText(QtGui.QApplication.translate("widgetOptInternet", "Configure Proxy for Download", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("widgetOptInternet", "You can choose any Pardus version and the download mirror (optional) from the list below. If you think that the version list is outdated, you can update it.", None, QtGui.QApplication.UnicodeUTF8))

