# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgetDownloading.ui'
#
# Created: Fri Jun 11 11:58:25 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_widgetDownloading(object):
    def setupUi(self, widgetDownloading):
        widgetDownloading.setObjectName("widgetDownloading")
        widgetDownloading.resize(446, 207)
        self.verticalLayoutWidget = QtGui.QWidget(widgetDownloading)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblProgress = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblProgress.setObjectName("lblProgress")
        self.horizontalLayout_3.addWidget(self.lblProgress)
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lblDescription = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblDescription.setObjectName("lblDescription")
        self.verticalLayout.addWidget(self.lblDescription)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblVersion = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblVersion.setObjectName("lblVersion")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblVersion)
        self.lblMirror = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblMirror.setObjectName("lblMirror")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblMirror)
        self.mirror = QtGui.QLabel(self.verticalLayoutWidget)
        self.mirror.setObjectName("mirror")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.mirror)
        self.lblStatus = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblStatus.setObjectName("lblStatus")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblStatus)
        self.status = QtGui.QLabel(self.verticalLayoutWidget)
        self.status.setWordWrap(False)
        self.status.setObjectName("status")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.status)
        self.lblSpeed = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblSpeed.setObjectName("lblSpeed")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblSpeed)
        self.speed = QtGui.QLabel(self.verticalLayoutWidget)
        self.speed.setObjectName("speed")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.speed)
        self.lblPercentage = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblPercentage.setObjectName("lblPercentage")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblPercentage)
        self.percentage = QtGui.QLabel(self.verticalLayoutWidget)
        self.percentage.setObjectName("percentage")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.percentage)
        self.lblCompleted = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCompleted.setObjectName("lblCompleted")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblCompleted)
        self.completed = QtGui.QLabel(self.verticalLayoutWidget)
        self.completed.setObjectName("completed")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.completed)
        self.lblETA = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblETA.setObjectName("lblETA")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblETA)
        self.ETA = QtGui.QLabel(self.verticalLayoutWidget)
        self.ETA.setObjectName("ETA")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.ETA)
        self.version = QtGui.QLabel(self.verticalLayoutWidget)
        self.version.setObjectName("version")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.version)
        self.verticalLayout.addLayout(self.formLayout_4)

        self.retranslateUi(widgetDownloading)
        QtCore.QMetaObject.connectSlotsByName(widgetDownloading)

    def retranslateUi(self, widgetDownloading):
        self.lblProgress.setText(QtGui.QApplication.translate("widgetDownloading", "Download Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescription.setText(QtGui.QApplication.translate("widgetDownloading", "Please standby while installation file is downloaded.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVersion.setText(QtGui.QApplication.translate("widgetDownloading", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMirror.setText(QtGui.QApplication.translate("widgetDownloading", "Mirror:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("widgetDownloading", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpeed.setText(QtGui.QApplication.translate("widgetDownloading", "Download Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.speed.setText(QtGui.QApplication.translate("widgetDownloading", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPercentage.setText(QtGui.QApplication.translate("widgetDownloading", "Percentage:", None, QtGui.QApplication.UnicodeUTF8))
        self.percentage.setText(QtGui.QApplication.translate("widgetDownloading", "0%", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCompleted.setText(QtGui.QApplication.translate("widgetDownloading", "Size Completed:", None, QtGui.QApplication.UnicodeUTF8))
        self.completed.setText(QtGui.QApplication.translate("widgetDownloading", "0 of 0 MB", None, QtGui.QApplication.UnicodeUTF8))
        self.lblETA.setText(QtGui.QApplication.translate("widgetDownloading", "ETA:", None, QtGui.QApplication.UnicodeUTF8))
        self.ETA.setText(QtGui.QApplication.translate("widgetDownloading", "N/A", None, QtGui.QApplication.UnicodeUTF8))

