# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Wed Aug 27 15:49:56 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Sahip(object):
    def setupUi(self, Sahip):
        Sahip.setObjectName("Sahip")
        Sahip.resize(605, 625)
        self.gridLayout_3 = QtGui.QGridLayout(Sahip)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(Sahip)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.languageBox = QtGui.QComboBox(Sahip)
        self.languageBox.setObjectName("languageBox")
        self.gridLayout_3.addWidget(self.languageBox, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(Sahip)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.variantBox = QtGui.QComboBox(Sahip)
        self.variantBox.setObjectName("variantBox")
        self.gridLayout_3.addWidget(self.variantBox, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(Sahip)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.splitter = QtGui.QSplitter(Sahip)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.rootPassword = QtGui.QLineEdit(self.splitter)
        self.rootPassword.setObjectName("rootPassword")
        self.shadowButton = QtGui.QPushButton(self.splitter)
        self.shadowButton.setObjectName("shadowButton")
        self.gridLayout_3.addWidget(self.splitter, 2, 1, 1, 2)
        self.label_4 = QtGui.QLabel(Sahip)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.timeZone = QtGui.QComboBox(Sahip)
        self.timeZone.setObjectName("timeZone")
        self.gridLayout_3.addWidget(self.timeZone, 3, 1, 1, 2)
        self.label_5 = QtGui.QLabel(Sahip)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.hostname = QtGui.QLineEdit(Sahip)
        self.hostname.setObjectName("hostname")
        self.gridLayout_3.addWidget(self.hostname, 4, 1, 1, 2)
        self.label_6 = QtGui.QLabel(Sahip)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtGui.QLabel(Sahip)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.username = QtGui.QLineEdit(Sahip)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(Sahip)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.realname = QtGui.QLineEdit(Sahip)
        self.realname.setObjectName("realname")
        self.gridLayout.addWidget(self.realname, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Sahip)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.password1 = QtGui.QLineEdit(Sahip)
        self.password1.setEchoMode(QtGui.QLineEdit.Password)
        self.password1.setObjectName("password1")
        self.gridLayout.addWidget(self.password1, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(Sahip)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.password2 = QtGui.QLineEdit(Sahip)
        self.password2.setEchoMode(QtGui.QLineEdit.Password)
        self.password2.setObjectName("password2")
        self.gridLayout.addWidget(self.password2, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Sahip)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupsOut = QtGui.QListWidget(Sahip)
        self.groupsOut.setObjectName("groupsOut")
        self.gridLayout_2.addWidget(self.groupsOut, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupAdd = QtGui.QToolButton(Sahip)
        self.groupAdd.setObjectName("groupAdd")
        self.verticalLayout_3.addWidget(self.groupAdd)
        self.groupDelete = QtGui.QToolButton(Sahip)
        self.groupDelete.setObjectName("groupDelete")
        self.verticalLayout_3.addWidget(self.groupDelete)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.groupsIn = QtGui.QListWidget(Sahip)
        self.groupsIn.setObjectName("groupsIn")
        self.gridLayout_2.addWidget(self.groupsIn, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.userList = QtGui.QListWidget(Sahip)
        self.userList.setObjectName("userList")
        self.gridLayout.addWidget(self.userList, 0, 2, 5, 1)
        self.userAdd = QtGui.QPushButton(Sahip)
        self.userAdd.setObjectName("userAdd")
        self.gridLayout.addWidget(self.userAdd, 5, 1, 1, 1)
        self.userDelete = QtGui.QPushButton(Sahip)
        self.userDelete.setObjectName("userDelete")
        self.gridLayout.addWidget(self.userDelete, 5, 2, 1, 1)
        self.label_12 = QtGui.QLabel(Sahip)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_13 = QtGui.QLabel(Sahip)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.autologinUserBox = QtGui.QComboBox(Sahip)
        self.autologinUserBox.setObjectName("autologinUserBox")
        self.gridLayout.addWidget(self.autologinUserBox, 6, 1, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 5, 2, 1, 1)
        self.label_14 = QtGui.QLabel(Sahip)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 2)
        self.partitioningTypeBox = QtGui.QComboBox(Sahip)
        self.partitioningTypeBox.setObjectName("partitioningTypeBox")
        self.gridLayout_3.addWidget(self.partitioningTypeBox, 6, 2, 1, 1)
        self.label_15 = QtGui.QLabel(Sahip)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 2)
        self.repoName = QtGui.QLineEdit(Sahip)
        self.repoName.setObjectName("repoName")
        self.gridLayout_3.addWidget(self.repoName, 9, 2, 1, 1)
        self.label_16 = QtGui.QLabel(Sahip)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 11, 0, 1, 2)
        self.repoAddress = QtGui.QLineEdit(Sahip)
        self.repoAddress.setObjectName("repoAddress")
        self.gridLayout_3.addWidget(self.repoAddress, 11, 2, 1, 1)
        self.generateXMLButton = QtGui.QPushButton(Sahip)
        self.generateXMLButton.setObjectName("generateXMLButton")
        self.gridLayout_3.addWidget(self.generateXMLButton, 12, 2, 1, 1)
        self.label_17 = QtGui.QLabel(Sahip)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 7, 0, 1, 1)
        self.disk = QtGui.QLineEdit(Sahip)
        self.disk.setObjectName("disk")
        self.gridLayout_3.addWidget(self.disk, 7, 2, 1, 1)

        self.retranslateUi(Sahip)
        QtCore.QMetaObject.connectSlotsByName(Sahip)
        Sahip.setTabOrder(self.languageBox, self.variantBox)
        Sahip.setTabOrder(self.variantBox, self.rootPassword)
        Sahip.setTabOrder(self.rootPassword, self.shadowButton)
        Sahip.setTabOrder(self.shadowButton, self.timeZone)
        Sahip.setTabOrder(self.timeZone, self.hostname)
        Sahip.setTabOrder(self.hostname, self.username)
        Sahip.setTabOrder(self.username, self.realname)
        Sahip.setTabOrder(self.realname, self.password1)
        Sahip.setTabOrder(self.password1, self.password2)
        Sahip.setTabOrder(self.password2, self.groupsOut)
        Sahip.setTabOrder(self.groupsOut, self.groupAdd)
        Sahip.setTabOrder(self.groupAdd, self.groupsIn)
        Sahip.setTabOrder(self.groupsIn, self.groupDelete)
        Sahip.setTabOrder(self.groupDelete, self.userAdd)
        Sahip.setTabOrder(self.userAdd, self.userList)
        Sahip.setTabOrder(self.userList, self.userDelete)
        Sahip.setTabOrder(self.userDelete, self.autologinUserBox)
        Sahip.setTabOrder(self.autologinUserBox, self.partitioningTypeBox)
        Sahip.setTabOrder(self.partitioningTypeBox, self.disk)
        Sahip.setTabOrder(self.disk, self.repoName)
        Sahip.setTabOrder(self.repoName, self.repoAddress)
        Sahip.setTabOrder(self.repoAddress, self.generateXMLButton)

    def retranslateUi(self, Sahip):
        Sahip.setWindowTitle(QtGui.QApplication.translate("Sahip", "Sahip", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Sahip", "Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Sahip", "Variant:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Sahip", "Root password:", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowButton.setText(QtGui.QApplication.translate("Sahip", "Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Sahip", "Time Zone:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Sahip", "Hostname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Sahip", "Users:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Sahip", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Sahip", "Real Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Sahip", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Sahip", "Password (again):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Sahip", "Groups:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupAdd.setText(QtGui.QApplication.translate("Sahip", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.groupDelete.setText(QtGui.QApplication.translate("Sahip", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.userAdd.setText(QtGui.QApplication.translate("Sahip", "Add User", None, QtGui.QApplication.UnicodeUTF8))
        self.userDelete.setText(QtGui.QApplication.translate("Sahip", "Delete User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Sahip", "Autologin User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Sahip", "Partitioning Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Sahip", "Repo Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Sahip", "Repo Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateXMLButton.setText(QtGui.QApplication.translate("Sahip", "Generate XML File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Sahip", "Disk:", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Sahip = QtGui.QWidget()
    ui = Ui_Sahip()
    ui.setupUi(Sahip)
    Sahip.show()
    sys.exit(app.exec_())

