#!/bin/sh

pxeboot() {
    FS_LOCATION='mnt/pxeboot'

    # Change directory to /newroot
    cd /newroot

    # FIXME: busybox mount does not load automatically
    modprobe -q nfs


    # mount nfs
    if [ -z "/etc/udhcpc.info" ]
    then
        fall2sh "/etc/udhcpc.info not found"
    fi

    . /etc/udhcpc.info

    if [ -z "${ROOTPATH}" ]
    then
        fall2sh "NFS rootpath not found"
    fi

    echo "Mounting NFS from $ROOTPATH"
    mount -o tcp,nolock,ro $ROOTPATH /newroot/mnt/thin

     # These are not loaded automatically
    modprobe -q squashfs

     # Loop type squashfs
    mount -t squashfs -o loop,ro /newroot/mnt/cdrom/${LOOPBACKFILE} /newroot/mnt/livecd

    if [ "$?" != "0" ]
    then
        fall2sh "Could not mount root image"
    fi

    # Create necessary links
    for x in ${ROOT_LINKS}; do
        ln -s "${FS_LOCATION}/${x}" "${x}"
    done

    if [ -e "${FS_LOCATION}/lib32" ]
    then
       ln -s "${FS_LOCATION}/lib32" "lib32"
    fi
 
     REAL_ROOT_TYPE=`echo "${ROOT_DEVICE}" | sed -e 's/^\/newroot\/dev\///' | grep -qE '^sr[0-9]*|^hd[a-z]|^pcd[0-9]|^xvd    *' && echo "optical" || echo "harddisk"`
    echo "${REAL_ROOT_TYPE}" > /newroot/var/run/pardus/livemedia

     # this is needed for yali
     MNTDIR=`grep \/mnt\/cdrom\  /proc/mounts|sed 's/\/newroot//g'`
     echo "$MNTDIR" >> /newroot/etc/fstab

}




#---------------------------------------------------------


elif [ "${PXEBOOT}" -eq "1"  ]
then
    ROOT_DEVICE=""

    run_dhcpc
    manage_tmpfs
    pxeboot

    # set hostname for mudur
    hostname $HOSTNAME


