#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2009, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

(GROUP_UNKNOWN, GROUP_ACCESSIBILITIY, GROUP_ACCESSORIES, GROUP_EDUCATION, GROUP_GAMES, GROUP_GRAPHICS,
 GROUP_INTERNET, GROUP_OFFICE, GROUP_OTHER, GROUP_PROGRAMMING, GROUP_MULTIMEDIA, GROUP_SYSTEM,
 GROUP_DESKTOP_KDE, GROUP_DESKTOP_GNOME, GROUP_DESKTOP_XFCE, GROUP_DESKTOP_OTHER, GROUP_PUBLISHING,
 GROUP_SERVERS, GROUP_FONTS, GROUP_ADMIN_TOOLS, GROUP_LEGACY, GROUP_LOCALIZATION, GROUP_VIRTUALIZATION,
 GROUP_POWER_MANAGEMENT, GROUP_SECURITY, GROUP_COMMUNICATION, GROUP_NETWORK, GROUP_MAPS, GROUP_SCIENCE,
 GROUP_ELECTRONICS, GROUP_DOCUMENTATION) = range(31)

groups = { GROUP_UNKNOWN : "Unknown",
           GROUP_ACCESSIBILITIY: "Accessibility",
           GROUP_ACCESSORIES: "Accessories",
           GROUP_EDUCATION: "Education",
           GROUP_GAMES: "Games",
           GROUP_GRAPHICS: "Graphics",
           GROUP_INTERNET: "Internet",
           GROUP_OFFICE: "Office",
           GROUP_OTHER: "Other",
           GROUP_PROGRAMMING: "Programming",
           GROUP_MULTIMEDIA: "Multimedia",
           GROUP_SYSTEM: "System",
           GROUP_DESKTOP_KDE: "KDE Desktop",
           GROUP_DESKTOP_GNOME: "Gnome Desktop",
           GROUP_DESKTOP_XFCE: "Xfce Desktop",
           GROUP_DESKTOP_OTHER: "Other Desktops",
           GROUP_PUBLISHING: "Publishing",
           GROUP_SERVERS: "Servers",
           GROUP_FONTS: "Fonts",
           GROUP_ADMIN_TOOLS: "Admin Tools",
           GROUP_LEGACY: "Legacy",
           GROUP_LOCALIZATION: "Localization",
           GROUP_VIRTUALIZATION: "Virtualization",
           GROUP_POWER_MANAGEMENT: "Power Management",
           GROUP_SECURITY: "Security",
           GROUP_COMMUNICATION: "Communication",
           GROUP_NETWORK: "Network",
           GROUP_MAPS: "Maps",
           GROUP_SCIENCE: "Science",
           GROUP_ELECTRONICS: "Electronics",
           GROUP_DOCUMENTATION: "Documentation"
}

component_group_mappings = {
    "applications" : GROUP_OTHER,
    "applications.admin" : GROUP_ADMIN_TOOLS,
    "applications.archive" : GROUP_OTHER,
    "applications.dictionaries" : GROUP_OTHER,
    "applications.dictionaries.aspell" : GROUP_OTHER,
    "applications.doc" : GROUP_PUBLISHING,
    "applications.doc.docbook" : GROUP_PUBLISHING,
    "applications.editors" : GROUP_ACCESSORIES,
    "applications.editors.emacs" : GROUP_ACCESSORIES,
    "applications.emulators" : GROUP_OTHER,
    "applications.filesystems" : GROUP_OTHER,
    "applications.games" : GROUP_GAMES,
    "applications.hardware" : GROUP_OTHER,
    "applications.hardware.smartcard" : GROUP_SECURITY,
    "applications.multimedia" : GROUP_MULTIMEDIA,
    "applications.network" : GROUP_INTERNET,
    "applications.network.amsn" : GROUP_INTERNET,
    "applications.network.mozilla" : GROUP_INTERNET,
    "applications.pda" : GROUP_ACCESSORIES,
    "applications.powermanagement" : GROUP_POWER_MANAGEMENT,
    "applications.printing" : GROUP_PUBLISHING,
    "applications.science" : GROUP_SCIENCE,
    "applications.science.astronomy" : GROUP_SCIENCE,
    "applications.science.electronics" : GROUP_SCIENCE,
    "applications.science.mathematics" : GROUP_EDUCATION,
    "applications.science.robotics" : GROUP_SCIENCE,
    "applications.security" : GROUP_SECURITY,
    "applications.shells" : GROUP_ADMIN_TOOLS,
    "applications.tex" : GROUP_PUBLISHING,
    "applications.util" : GROUP_ACCESSORIES,
    "applications.virtualization" : GROUP_VIRTUALIZATION,
    "desktop.enlightenment" : GROUP_DESKTOP_OTHER,
    "desktop.enlightenment.base" : GROUP_DESKTOP_OTHER,
    "desktop.fluxbox" : GROUP_DESKTOP_OTHER,
    "desktop.fonts" : GROUP_FONTS,
    "desktop.freedesktop" : GROUP_DESKTOP_OTHER,
    "desktop.freedesktop.xorg" : GROUP_DESKTOP_OTHER,
    "desktop.freedesktop.xorg.lib" : GROUP_DESKTOP_OTHER,
    "desktop.gnome" : GROUP_DESKTOP_GNOME,
    "desktop.gnome.base" : GROUP_DESKTOP_GNOME,
    "desktop.kde" : GROUP_DESKTOP_KDE,
    "desktop.kde.base" : GROUP_DESKTOP_KDE,
    "desktop.kde.i18n" : GROUP_LOCALIZATION,
    "desktop.kde4" : GROUP_DESKTOP_KDE,
    "desktop.kde4.base" : GROUP_DESKTOP_KDE,
    "desktop.kde4.i18n" : GROUP_LOCALIZATION,
    "desktop.opencompositing" : GROUP_DESKTOP_OTHER,
    "desktop.opencompositing.cairo" : GROUP_DESKTOP_OTHER,
    "desktop.opencompositing.compiz" : GROUP_DESKTOP_OTHER,
    "desktop.opencompositing.kiba" : GROUP_DESKTOP_OTHER,
    "desktop.xfce4" : GROUP_DESKTOP_XFCE,
    "desktop.xfce4.base" : GROUP_DESKTOP_XFCE,
    "desktop.xfce4.goodies" : GROUP_DESKTOP_XFCE,
    "desktop.xfce4.themes" : GROUP_DESKTOP_XFCE,
    "kernel" : GROUP_SYSTEM,
    "kernel.drivers" : GROUP_SYSTEM,
    "kernel.firmware" : GROUP_SYSTEM,
    "programming" : GROUP_PROGRAMMING,
    "programming.environments" : GROUP_PROGRAMMING,
    "programming.environments.eclipse" : GROUP_PROGRAMMING,
    "programming.environments.eric" : GROUP_PROGRAMMING,
    "programming.languages" : GROUP_PROGRAMMING,
    "programming.languages.dotnet" : GROUP_PROGRAMMING,
    "programming.languages.gambas" : GROUP_PROGRAMMING,
    "programming.languages.haskell" : GROUP_PROGRAMMING,
    "programming.languages.java" : GROUP_PROGRAMMING,
    "programming.languages.lisp" : GROUP_PROGRAMMING,
    "programming.languages.pascal" : GROUP_PROGRAMMING,
    "programming.languages.perl" : GROUP_PROGRAMMING,
    "programming.languages.php" : GROUP_PROGRAMMING,
    "programming.languages.python" : GROUP_PROGRAMMING,
    "programming.languages.python.django" : GROUP_PROGRAMMING,
    "programming.languages.tcl" : GROUP_PROGRAMMING,
    "programming.libs" : GROUP_PROGRAMMING,
    "programming.tools" : GROUP_PROGRAMMING,
    "ptsp" : GROUP_SERVERS,
    "server" : GROUP_SERVERS,
    "server.database" : GROUP_SERVERS,
    "server.mail" : GROUP_SERVERS,
    "server.nis" : GROUP_SERVERS,
    "server.www" : GROUP_SERVERS,
    "system" : GROUP_SYSTEM,
    "system.base" : GROUP_SYSTEM,
    "system.devel" : GROUP_PROGRAMMING,
    "system.doc" : GROUP_SYSTEM,
    "system.locale" : GROUP_LOCALIZATION
}
