
#!/usr/bin/env python
# Generated by pykdeuic4 from ui.item.ui on Wed Feb 25 14:51:45 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_PackageWidget(object):
    def setupUi(self, PackageWidget):
        PackageWidget.setObjectName("PackageWidget")
        PackageWidget.resize(568, 48)
        PackageWidget.setMinimumSize(QtCore.QSize(0, 48))
        self.gridLayout_2 = QtGui.QGridLayout(PackageWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkState = QtGui.QCheckBox(PackageWidget)
        self.checkState.setObjectName("checkState")
        self.gridLayout_2.addWidget(self.checkState, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtGui.QLabel(PackageWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.labelSummary = QtGui.QLabel(PackageWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelSummary.setFont(font)
        self.labelSummary.setStyleSheet("color:gray;")
        self.labelSummary.setObjectName("labelSummary")
        self.verticalLayout.addWidget(self.labelSummary)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(308, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.labelStatus = QtGui.QLabel(PackageWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(36, 0))
        self.labelStatus.setPixmap(QtGui.QPixmap("icons/package.png"))
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_2.addWidget(self.labelStatus, 0, 1, 1, 1)

        self.retranslateUi(PackageWidget)
        QtCore.QMetaObject.connectSlotsByName(PackageWidget)

    def retranslateUi(self, PackageWidget):
        PackageWidget.setWindowTitle(kdecore.i18n("Form"))
        self.labelName.setText(kdecore.i18n("Package name"))
        self.labelSummary.setText(kdecore.i18n("Package summary"))

import data_rc
