#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from main.ui on Mon Sep 14 09:10:29 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(666, 561)
        MainWidget.setWindowTitle("MainWidget")
        self.verticalLayout = QtGui.QVBoxLayout(MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameList = QtGui.QFrame(MainWidget)
        self.frameList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameList.setFrameShadow(QtGui.QFrame.Raised)
        self.frameList.setObjectName("frameList")
        self.gridLayout_2 = QtGui.QGridLayout(self.frameList)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushNew = QtGui.QToolButton(self.frameList)
        self.pushNew.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.pushNew.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushNew.setArrowType(QtCore.Qt.NoArrow)
        self.pushNew.setObjectName("pushNew")
        self.horizontalLayout_3.addWidget(self.pushNew)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.listItems = QtGui.QListWidget(self.frameList)
        self.listItems.setObjectName("listItems")
        self.gridLayout_2.addWidget(self.listItems, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frameList)
        self.frameEdit = QtGui.QFrame(MainWidget)
        self.frameEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEdit.setObjectName("frameEdit")
        self.gridLayout_3 = QtGui.QGridLayout(self.frameEdit)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonBox = QtGui.QDialogButtonBox(self.frameEdit)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.scrollWidget = QtGui.QScrollArea(self.frameEdit)
        self.scrollWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollWidget.setWidgetResizable(True)
        self.scrollWidget.setObjectName("scrollWidget")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollWidget)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 644, 232))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.frameWidget = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameWidget.setObjectName("frameWidget")
        self.gridLayout.addWidget(self.frameWidget, 0, 0, 1, 1)
        self.scrollWidget.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frameEdit)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)
        MainWidget.setTabOrder(self.listItems, self.buttonBox)

    def retranslateUi(self, MainWidget):
        self.pushNew.setText(kdecore.i18n("Find Services"))

