#!/usr/bin/python

## Load the builders
env = Environment( tools = ["default", "generic", "kde"], toolpath = ["./admin"])

# Set the build directory so we can do "rm -rf build" to clean up.
BuildDir("build/src", "src")

env.KDEuse("environ")

obj=env.kobject("program")
obj.target="kio-to-local"

obj.source="main.cpp"

obj.libs="kio kdecore qt-mt"
obj.execute()

# CONVENIENCE FUNCTIONS TO EMULATE "make dist" and "make distclean"
env.dist("kio-to-local")
