#!/usr/bin/python
# -*- coding: utf-8 -*-

# Standard Python Library
from getpass import getpass
from optparse import OptionParser
import os
import os.path
import sys

# PLSA Library
import plsa
import plsa.utility
from plsa.gpg import GPG

# piksemel
import piksemel

# i18n
import gettext
__trans = gettext.translation("plsa", fallback=True)
_ = __trans.ugettext

# Error codes
SUCCESS, FAIL_USAGE, FAIL_READ, FAIL_WRITE, \
FAIL_XML, FAIL_KEY, FAIL_PP, FAIL_LANG = xrange(8)

def main():
    language = os.environ["LANG"][:2]

    version = "1.0"
    usage = "%prog <options> advisory.xml"

    parser = OptionParser(usage=usage,  version="%prog " + version)
    parser.add_option("-s", "--sign", dest="sign",
                      help=_("sign advisory with KEY"), metavar=_("KEY"))
    parser.add_option("-p", "--pass", dest="passphrase",
                      help=_("use PASS as passphrase"), metavar=_("PASS"))
    parser.add_option("-l", "--language", dest="language",
                      help=_("generate advisory for locale LANG (default: %s)") % language, metavar=_("LANG"))
    parser.add_option("-o", "--output", dest="output",
                      help=_("save advisory text to FILE"), metavar=_("FILE"))
    options, args = parser.parse_args()

    if len(args) == 0:
        parser.print_help()
        return FAIL_USAGE

    if not options.language:
        options.language = language

    if options.language not in plsa.utility.list_translations("plsa"):
        print _("'%s' locale is not supported.")
        return FAIL_LANG

    # Read advisory xml
    if not os.path.isfile(args[0]) or not os.access(args[0], os.R_OK):
        print _("Unable to read %s.") % args[0]
        return FAIL_READ

    adv = plsa.advisory(options.language)

    try:
        adv.import_xml(args[0])
    except:
        print _("XML file has errors:")
        for i in adv.errors:
            print "  " + i
        return FAIL_XML

    # Build advisory text
    text = adv.build_text()

    # Sign advisory
    if options.sign:
        gnupg = GPG()
        if options.sign not in [x["keyid"][-8:] for x in gnupg.list_keys(secret=True)]:
            print _("Key not found in GnuPG database.")
            print _("Available keys are:")
            for i in gnupg.list_keys(secret=1):
                print "  %s - %s" % (i["keyid"][-8:], i["uids"][1])
            return FAIL_KEY
        else:
            if not options.passphrase:
                options.passphrase = getpass(_("Passphrase: "))
            text_signed = gnupg.sign(text, options.sign, options.passphrase)
            if not str(text_signed):
                print _("Invalid passphrase.")
                return FAIL_PP
            else:
                text = text_signed

    if options.output:
        try:
            open(options.output, "w").write(text)
        except IOError:
            print _("Unable to write advisory text to %s") % options.output
            return FAIL_WRITE
    else:
        print text

    return SUCCESS

if __name__ == "__main__":
    sys.exit(main())
