######################################################################
# Automatically generated by qmake (1.07a) Mon May 16 20:58:55 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += anapencere.h dictreader.h editdialog.h gozluksettings.h
SOURCES += anapencere.cpp \
           dictreader.cpp \
           editdialog.cpp \
           gozluksettings.cpp \
           main.cpp
