#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from item.ui on Mon Sep  7 11:02:03 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ServiceItemWidget(object):
    def setupUi(self, ServiceItemWidget):
        ServiceItemWidget.setObjectName("ServiceItemWidget")
        ServiceItemWidget.resize(234, 48)
        ServiceItemWidget.setMinimumSize(QtCore.QSize(0, 48))
        self.labelStatus = QtGui.QLabel(ServiceItemWidget)
        self.labelStatus.setGeometry(QtCore.QRect(4, 16, 36, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(36, 0))
        self.labelStatus.setPixmap(QtGui.QPixmap("icons/stopped.png"))
        self.labelStatus.setObjectName("labelStatus")
        self.labelName = QtGui.QLabel(ServiceItemWidget)
        self.labelName.setGeometry(QtCore.QRect(45, 7, 95, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.widget = QtGui.QWidget(ServiceItemWidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelDesc = QtGui.QLabel(ServiceItemWidget)
        self.labelDesc.setGeometry(QtCore.QRect(45, 26, 58, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelDesc.setFont(font)
        self.labelDesc.setStyleSheet("color:gray;")
        self.labelDesc.setObjectName("labelDesc")

        self.retranslateUi(ServiceItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ServiceItemWidget)

    def retranslateUi(self, ServiceItemWidget):
        ServiceItemWidget.setWindowTitle(kdecore.i18n("Form"))
        self.labelName.setText(kdecore.i18n("ServiceName"))
        self.labelDesc.setText(kdecore.i18n("ServiceIp"))

