#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from item.ui on Mon Sep 14 14:03:30 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ItemWidget(object):
    def setupUi(self, ItemWidget):
        ItemWidget.setObjectName("ItemWidget")
        ItemWidget.resize(193, 48)
        ItemWidget.setWindowTitle("ItemWidget")
        self.gridLayout = QtGui.QGridLayout(ItemWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtGui.QLabel(ItemWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setText("labelTitle")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.labelDescription = QtGui.QLabel(ItemWidget)
        self.labelDescription.setText("labelDescription")
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout.addWidget(self.labelDescription)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.labelIcon = QtGui.QLabel(ItemWidget)
        self.labelIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.labelIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIcon.setObjectName("labelIcon")
        self.gridLayout.addWidget(self.labelIcon, 0, 0, 1, 1)

        self.retranslateUi(ItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ItemWidget)

    def retranslateUi(self, ItemWidget):
        pass

