#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
    Software magement module
"""

# Qt4 modules
from PyQt4 import QtGui
from PyQt4 import QtCore

# Generated UI module
from plugins.plugin_authentication.ui_authentication import Ui_widgetAuthentication

# Helper modules
from helpers import plugins
from helpers import wrappers


class WidgetModule(QtGui.QWidget, Ui_widgetAuthentication, plugins.PluginWidget):
    """
        Software management UI.
    """
    def __init__(self, parent=None):
        """
            Constructor for main window.

            Arguments:
                parent: Parent object
        """
        plugins.PluginWidget.__init__(self)
        QtGui.QWidget.__init__(self, parent)

        # Attach generated UI
        self.setupUi(self)

        # UI events
        self.connect(self.radioUnix, QtCore.SIGNAL("clicked()"), self.__update_boxes)
        self.connect(self.radioLDAP, QtCore.SIGNAL("clicked()"), self.__update_boxes)
        self.connect(self.radioAD, QtCore.SIGNAL("clicked()"), self.__update_boxes)

        # Reset UI
        self.__update_boxes()

    def showEvent(self, event):
        """
            Things to do before widget is shown.
        """
        pass

    def get_type(self):
        """
            Widget type.

            Should return TYPE_GLOBAL or TYPE_SINGLE
        """
        return plugins.TYPE_SINGLE

    def load_policy(self, policy):
        """
            Main window calls this method when policy is fetched from directory.
            Not required for global widgets.
        """
        pass

    def dump_policy(self):
        """
            Main window calls this method to get policy generated by UI.
            Not required for global widgets.
        """
        policy = {
        }
        return policy

    def talk_message(self, sender, command, arguments=None):
        """
            Main window calls this method when an XMPP message is received.
        """
        pass

    def talk_status(self, sender, status):
        """
            Main window calls this method when an XMPP status is changed.
        """
        pass

    def __update_boxes(self):
        """
            Changes visibilities of group boxes according to authentication
            source selection.
        """
        if self.radioUnix.isChecked():
            self.groupLDAP.hide()
            self.groupAD.hide()
        elif self.radioLDAP.isChecked():
            self.groupLDAP.show()
            self.groupAD.hide()
        elif self.radioAD.isChecked():
            self.groupLDAP.hide()
            self.groupAD.show()
