# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/s/testing-framework/src/testcases/ui/main.ui'
#
# Created: Tue Aug 10 07:31:05 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(601, 631)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 581, 431))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.text_edit = QtGui.QTextEdit(self.groupBox)
        self.text_edit.setEnabled(False)
        self.text_edit.setGeometry(QtCore.QRect(10, 60, 561, 431))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.text_edit.setFont(font)
        self.text_edit.setObjectName("text_edit")
        self.package_label = QtGui.QLabel(self.groupBox)
        self.package_label.setGeometry(QtCore.QRect(210, 30, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.package_label.setFont(font)
        self.package_label.setObjectName("package_label")
        self.text_observation = QtGui.QPlainTextEdit(Dialog)
        self.text_observation.setGeometry(QtCore.QRect(40, 520, 531, 70))
        self.text_observation.setObjectName("text_observation")
        self.clear_button = QtGui.QPushButton(Dialog)
        self.clear_button.setGeometry(QtCore.QRect(40, 600, 51, 25))
        self.clear_button.setObjectName("clear_button")
        self.next_button = QtGui.QPushButton(Dialog)
        self.next_button.setGeometry(QtCore.QRect(499, 600, 71, 25))
        self.next_button.setObjectName("next_button")
        self.quit_button = QtGui.QPushButton(Dialog)
        self.quit_button.setEnabled(False)
        self.quit_button.setGeometry(QtCore.QRect(420, 600, 71, 25))
        self.quit_button.setObjectName("quit_button")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 460, 561, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.yes_button = QtGui.QRadioButton(self.layoutWidget)
        self.yes_button.setChecked(False)
        self.yes_button.setObjectName("yes_button")
        self.gridLayout.addWidget(self.yes_button, 0, 2, 1, 1)
        self.no_button = QtGui.QRadioButton(self.layoutWidget)
        self.no_button.setChecked(True)
        self.no_button.setObjectName("no_button")
        self.gridLayout.addWidget(self.no_button, 0, 4, 1, 1)
        self.unable_button = QtGui.QRadioButton(self.layoutWidget)
        self.unable_button.setObjectName("unable_button")
        self.gridLayout.addWidget(self.unable_button, 0, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.yes_button, QtCore.SIGNAL("clicked(bool)"), self.text_observation.setDisabled)
        QtCore.QObject.connect(self.clear_button, QtCore.SIGNAL("clicked()"), self.text_observation.clear)
        QtCore.QObject.connect(self.yes_button, QtCore.SIGNAL("clicked(bool)"), self.label_2.setDisabled)
        QtCore.QObject.connect(self.quit_button, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QObject.connect(self.no_button, QtCore.SIGNAL("clicked(bool)"), self.text_observation.setEnabled)
        QtCore.QObject.connect(self.no_button, QtCore.SIGNAL("clicked(bool)"), self.label_2.setEnabled)
        QtCore.QObject.connect(self.unable_button, QtCore.SIGNAL("clicked(bool)"), self.text_observation.setDisabled)
        QtCore.QObject.connect(self.unable_button, QtCore.SIGNAL("clicked(bool)"), self.label_2.setDisabled)
        QtCore.QObject.connect(self.yes_button, QtCore.SIGNAL("clicked(bool)"), self.clear_button.setDisabled)
        QtCore.QObject.connect(self.unable_button, QtCore.SIGNAL("clicked(bool)"), self.clear_button.setDisabled)
        QtCore.QObject.connect(self.no_button, QtCore.SIGNAL("clicked(bool)"), self.clear_button.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.yes_button, self.no_button)
        Dialog.setTabOrder(self.no_button, self.text_observation)
        Dialog.setTabOrder(self.text_observation, self.next_button)
        Dialog.setTabOrder(self.next_button, self.clear_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Pardus Testing Framework", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("Dialog", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.next_button.setText(QtGui.QApplication.translate("Dialog", "N&ext", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_button.setText(QtGui.QApplication.translate("Dialog", "&Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Did the above test work as expected?", None, QtGui.QApplication.UnicodeUTF8))
        self.yes_button.setText(QtGui.QApplication.translate("Dialog", "&Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.no_button.setText(QtGui.QApplication.translate("Dialog", "&No", None, QtGui.QApplication.UnicodeUTF8))
        self.unable_button.setText(QtGui.QApplication.translate("Dialog", "&Unable to peform this test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Enter your observation: ", None, QtGui.QApplication.UnicodeUTF8))

