######################################################################
# Automatically generated by qmake (1.07a) Fri Jan 7 20:46:01 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
CONFIG += qt debug

# Input
HEADERS += dictreader.h gozluksettings.h gozlukwin.h
SOURCES += dictreader.cpp gozluksettings.h gozlukwin.cpp main.cpp
