all:
	./ahenk_schema 1 softwarePolicy schema_templates/software.txt > schema/ahenk_software.schema
	./ahenk_schema 2 authenticationPolicy schema_templates/authentication.txt > schema/ahenk_authentication.schema
