all:
	./make_schema.py 1 softwarePolicy schema_templates/software.txt > schema/ahenk_software.schema
	./make_schema.py 2 authenticationPolicy schema_templates/authentication.txt > schema/ahenk_authentication.schema
