#!/usr/bin/python

import os
import sys
import distutils.sysconfig

# Parameters

version = ARGUMENTS.get('version', '1.2')
prefix = ARGUMENTS.get('prefix', 'install')

# Source Distribution

distfiles = """
    SConstruct
    pyiks.c
    iksemel.c
    iksemel.h
    README
    perftest.py
    test.py
"""

if 'dist' in sys.argv:
    os.popen("tar -czf %s %s" % ("piksemel-" + version + ".tar.gz", " ".join(Split(distfiles))))
    Exit(0)

# Configuration

if sys.version_info[1] == 3:
    pyprefix = 'usr/lib/python2.3/site-packages'
else:
    pyprefix = 'usr/lib/python2.4/site-packages'

pydir = os.path.join(prefix, pyprefix)

# Build

vars = distutils.sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'BASECFLAGS', 'CCSHARED', 'LDSHARED', 'SO')
for i in range(len(vars)):
    if vars[i] is None:
        vars[i] = ""

(cc, cxx, opt, basecflags, ccshared, ldshared, so_ext) = vars

pyiks = SharedLibrary("piksemel",
                    ["pyiks.c", "iksemel.c"],
                    CC=cc,
                    SHLINK=ldshared,
                    SHLINKFLAGS=[],
                    SHLIBPREFIX="",
                    SHLIBSUFFIX=so_ext,
                    CPPPATH=[distutils.sysconfig.get_python_inc()],
                    CPPFLAGS=basecflags + " " + opt + " -Wall -O2")

if type(pyiks) == type([]): pyiks = pyiks[0]

# Install

targets = []
targets.append(Install(pydir, pyiks))

Alias('install', targets)
