# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgetConfiguration.ui'
#
# Created: Mon Jun 14 20:48:50 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_widgetConfiguration(object):
    def setupUi(self, widgetConfiguration):
        widgetConfiguration.setObjectName("widgetConfiguration")
        widgetConfiguration.resize(416, 216)
        widgetConfiguration.setWindowTitle("")
        self.formLayoutWidget = QtGui.QWidget(widgetConfiguration)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 3, 301, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblDrive = QtGui.QLabel(self.formLayoutWidget)
        self.lblDrive.setObjectName("lblDrive")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblDrive)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sizeSlider = QtGui.QSlider(self.formLayoutWidget)
        self.sizeSlider.setSingleStep(1)
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setObjectName("sizeSlider")
        self.horizontalLayout_2.addWidget(self.sizeSlider)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbFreeSpace = QtGui.QProgressBar(self.formLayoutWidget)
        self.pbFreeSpace.setProperty("value", 0)
        self.pbFreeSpace.setObjectName("pbFreeSpace")
        self.horizontalLayout_3.addWidget(self.pbFreeSpace)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.hLine = QtGui.QFrame(self.formLayoutWidget)
        self.hLine.setFrameShape(QtGui.QFrame.HLine)
        self.hLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.hLine.setObjectName("hLine")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.hLine)
        self.lblUsername = QtGui.QLabel(self.formLayoutWidget)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblUsername)
        self.txtUsername = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtUsername)
        self.lblPassword = QtGui.QLabel(self.formLayoutWidget)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.LblRetypePassword = QtGui.QLabel(self.formLayoutWidget)
        self.LblRetypePassword.setObjectName("LblRetypePassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.LblRetypePassword)
        self.txtRetypePassword = QtGui.QLineEdit(self.formLayoutWidget)
        self.txtRetypePassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtRetypePassword.setObjectName("txtRetypePassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.txtRetypePassword)
        self.lblFree = QtGui.QLabel(self.formLayoutWidget)
        self.lblFree.setObjectName("lblFree")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblFree)
        self.lblInstallation = QtGui.QLabel(self.formLayoutWidget)
        self.lblInstallation.setObjectName("lblInstallation")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblInstallation)
        self.comboDrive = QtGui.QComboBox(self.formLayoutWidget)
        self.comboDrive.setObjectName("comboDrive")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboDrive)
        self.lblFreeLeft = QtGui.QLabel(widgetConfiguration)
        self.lblFreeLeft.setGeometry(QtCore.QRect(310, 70, 101, 23))
        self.lblFreeLeft.setObjectName("lblFreeLeft")
        self.lblSize = QtGui.QLabel(widgetConfiguration)
        self.lblSize.setGeometry(QtCore.QRect(310, 40, 101, 23))
        self.lblSize.setObjectName("lblSize")
        self.lblDriveFreeSpace = QtGui.QLabel(widgetConfiguration)
        self.lblDriveFreeSpace.setGeometry(QtCore.QRect(310, 10, 101, 25))
        self.lblDriveFreeSpace.setObjectName("lblDriveFreeSpace")

        self.retranslateUi(widgetConfiguration)
        QtCore.QMetaObject.connectSlotsByName(widgetConfiguration)

    def retranslateUi(self, widgetConfiguration):
        self.lblDrive.setText(QtGui.QApplication.translate("widgetConfiguration", "Installation Drive", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setText(QtGui.QApplication.translate("widgetConfiguration", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("widgetConfiguration", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.LblRetypePassword.setText(QtGui.QApplication.translate("widgetConfiguration", "Retype Password ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFree.setText(QtGui.QApplication.translate("widgetConfiguration", "After Installation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInstallation.setText(QtGui.QApplication.translate("widgetConfiguration", "Installation Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreeLeft.setText(QtGui.QApplication.translate("widgetConfiguration", "GB free", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSize.setText(QtGui.QApplication.translate("widgetConfiguration", " GB", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDriveFreeSpace.setText(QtGui.QApplication.translate("widgetConfiguration", "GB free", None, QtGui.QApplication.UnicodeUTF8))

