#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from gui/widgets/bugtoolMain.ui on Sun Aug 16 23:30:54 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_bugtoolUI(object):
    def setupUi(self, bugtoolUI):
        bugtoolUI.setObjectName("bugtoolUI")
        bugtoolUI.resize(700, 500)
        bugtoolUI.setStyleSheet("""
#bugtool{
    
       background-image:url(':/raw/pics/bg.png');
       background-repeat: no-repeat;
       background-position: left top;
       background-color: #642437;
       alternate-background-color: gray;
       selection-background-color: gray;

}

QStackedWidget#mainStack {
    color: white;
     border-style: outset;
     border-width: 1px;
     border-radius: 10px;
     border-color: rgba(255, 255, 255, 152);

}
""")
        self.gridLayout_3 = QtGui.QGridLayout(bugtoolUI)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bugtool = QtGui.QWidget(bugtoolUI)
        self.bugtool.setObjectName("bugtool")
        self.gridLayout_2 = QtGui.QGridLayout(self.bugtool)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelMenu = QtGui.QLabel(self.bugtool)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelMenu.setFont(font)
        self.labelMenu.setAutoFillBackground(False)
        self.labelMenu.setStyleSheet("color:black")
        self.labelMenu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMenu.setIndent(10)
        self.labelMenu.setObjectName("labelMenu")
        self.gridLayout.addWidget(self.labelMenu, 1, 0, 3, 3)
        self.labelLogo = QtGui.QLabel(self.bugtool)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setMinimumSize(QtCore.QSize(80, 80))
        self.labelLogo.setStyleSheet("margin-left:14px;")
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout.addWidget(self.labelLogo, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.mainStack = QtGui.QStackedWidget(self.bugtool)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStack.sizePolicy().hasHeightForWidth())
        self.mainStack.setSizePolicy(sizePolicy)
        self.mainStack.setStyleSheet("""QStackedWidget#mainStack{background-color:rgba(255, 255, 255,200);
margin: 10px;
}""")
        self.mainStack.setLineWidth(0)
        self.mainStack.setObjectName("mainStack")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.mainStack.addWidget(self.page)
        self.verticalLayout_4.addWidget(self.mainStack)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCancel = QtGui.QPushButton(self.bugtool)
        self.buttonCancel.setStyleSheet("color:black")
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_2.addWidget(self.buttonCancel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonNext = QtGui.QPushButton(self.bugtool)
        self.buttonNext.setStyleSheet("color:black")
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout_2.addWidget(self.buttonNext)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.bugtool, 0, 0, 1, 1)

        self.retranslateUi(bugtoolUI)
        self.mainStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bugtoolUI)

    def retranslateUi(self, bugtoolUI):
        bugtoolUI.setWindowTitle(kdecore.i18n("Bug Reporting Tool"))
        self.buttonCancel.setText(kdecore.i18n("Cancel"))
        self.buttonNext.setText(kdecore.i18n("Next"))

import raw_rc
