# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bug_reporter.ui'
#
# Created: Fri Aug 19 09:10:37 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BugReporter(object):
    def setupUi(self, BugReporter):
        BugReporter.setObjectName(_fromUtf8("BugReporter"))
        BugReporter.resize(595, 527)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BugReporter.sizePolicy().hasHeightForWidth())
        BugReporter.setSizePolicy(sizePolicy)
        BugReporter.setMaximumSize(QtCore.QSize(595, 527))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/warning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BugReporter.setWindowIcon(icon)
        BugReporter.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(BugReporter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 581, 481))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName(_fromUtf8("page1"))
        self.frameTitlePage1 = QtGui.QFrame(self.page1)
        self.frameTitlePage1.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage1.setStyleSheet(_fromUtf8("#frameTitlePage1{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage1.setObjectName(_fromUtf8("frameTitlePage1"))
        self.lblTitlePae1 = QtGui.QLabel(self.frameTitlePage1)
        self.lblTitlePae1.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePae1.setFont(font)
        self.lblTitlePae1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePae1.setWordWrap(True)
        self.lblTitlePae1.setObjectName(_fromUtf8("lblTitlePae1"))
        self.frameWelcomeMessage = QtGui.QFrame(self.page1)
        self.frameWelcomeMessage.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameWelcomeMessage.setStyleSheet(_fromUtf8("#frameWelcomeMessage{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameWelcomeMessage.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameWelcomeMessage.setFrameShadow(QtGui.QFrame.Raised)
        self.frameWelcomeMessage.setObjectName(_fromUtf8("frameWelcomeMessage"))
        self.lblquestionPage1 = QtGui.QLabel(self.frameWelcomeMessage)
        self.lblquestionPage1.setGeometry(QtCore.QRect(20, 20, 521, 331))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblquestionPage1.setFont(font)
        self.lblquestionPage1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblquestionPage1.setWordWrap(True)
        self.lblquestionPage1.setObjectName(_fromUtf8("lblquestionPage1"))
        self.btnNextPage1 = QtGui.QPushButton(self.page1)
        self.btnNextPage1.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnNextPage1.setObjectName(_fromUtf8("btnNextPage1"))
        self.btnCancelPage1 = QtGui.QPushButton(self.page1)
        self.btnCancelPage1.setGeometry(QtCore.QRect(430, 440, 68, 31))
        self.btnCancelPage1.setObjectName(_fromUtf8("btnCancelPage1"))
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setObjectName(_fromUtf8("page2"))
        self.frameTitlePage2 = QtGui.QFrame(self.page2)
        self.frameTitlePage2.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage2.setStyleSheet(_fromUtf8("#frameTitlePage2{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage2.setObjectName(_fromUtf8("frameTitlePage2"))
        self.lblTitlePage2 = QtGui.QLabel(self.frameTitlePage2)
        self.lblTitlePage2.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePage2.setFont(font)
        self.lblTitlePage2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePage2.setWordWrap(True)
        self.lblTitlePage2.setObjectName(_fromUtf8("lblTitlePage2"))
        self.frameProducts = QtGui.QFrame(self.page2)
        self.frameProducts.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameProducts.setStyleSheet(_fromUtf8("#frameProducts{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameProducts.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameProducts.setFrameShadow(QtGui.QFrame.Raised)
        self.frameProducts.setObjectName(_fromUtf8("frameProducts"))
        self.rbDisplay = QtGui.QRadioButton(self.frameProducts)
        self.rbDisplay.setGeometry(QtCore.QRect(20, 60, 521, 21))
        self.rbDisplay.setObjectName(_fromUtf8("rbDisplay"))
        self.lblquestion = QtGui.QLabel(self.frameProducts)
        self.lblquestion.setGeometry(QtCore.QRect(20, 20, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblquestion.setFont(font)
        self.lblquestion.setWordWrap(True)
        self.lblquestion.setObjectName(_fromUtf8("lblquestion"))
        self.rbStorage = QtGui.QRadioButton(self.frameProducts)
        self.rbStorage.setGeometry(QtCore.QRect(20, 100, 521, 21))
        self.rbStorage.setObjectName(_fromUtf8("rbStorage"))
        self.rbSoundAudio = QtGui.QRadioButton(self.frameProducts)
        self.rbSoundAudio.setGeometry(QtCore.QRect(20, 140, 521, 21))
        self.rbSoundAudio.setObjectName(_fromUtf8("rbSoundAudio"))
        self.rbOthers = QtGui.QRadioButton(self.frameProducts)
        self.rbOthers.setGeometry(QtCore.QRect(20, 180, 521, 21))
        self.rbOthers.setObjectName(_fromUtf8("rbOthers"))
        self.btnBackPage2 = QtGui.QPushButton(self.page2)
        self.btnBackPage2.setGeometry(QtCore.QRect(430, 440, 68, 31))
        self.btnBackPage2.setObjectName(_fromUtf8("btnBackPage2"))
        self.btnNextPage2 = QtGui.QPushButton(self.page2)
        self.btnNextPage2.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnNextPage2.setObjectName(_fromUtf8("btnNextPage2"))
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtGui.QWidget()
        self.page3.setObjectName(_fromUtf8("page3"))
        self.frameDetails = QtGui.QFrame(self.page3)
        self.frameDetails.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameDetails.setStyleSheet(_fromUtf8("#frameDetails{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameDetails.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDetails.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDetails.setObjectName(_fromUtf8("frameDetails"))
        self.lblSteps = QtGui.QLabel(self.frameDetails)
        self.lblSteps.setGeometry(QtCore.QRect(40, 220, 71, 16))
        self.lblSteps.setObjectName(_fromUtf8("lblSteps"))
        self.txtSummary = QtGui.QTextEdit(self.frameDetails)
        self.txtSummary.setGeometry(QtCore.QRect(130, 20, 411, 31))
        self.txtSummary.setLineWidth(1)
        self.txtSummary.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.txtSummary.setLineWrapColumnOrWidth(1)
        self.txtSummary.setObjectName(_fromUtf8("txtSummary"))
        self.lblSummary = QtGui.QLabel(self.frameDetails)
        self.lblSummary.setGeometry(QtCore.QRect(40, 30, 71, 16))
        self.lblSummary.setObjectName(_fromUtf8("lblSummary"))
        self.lblDetails = QtGui.QLabel(self.frameDetails)
        self.lblDetails.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.lblDetails.setObjectName(_fromUtf8("lblDetails"))
        self.txtDetails = QtGui.QTextEdit(self.frameDetails)
        self.txtDetails.setGeometry(QtCore.QRect(130, 60, 411, 121))
        self.txtDetails.setLineWidth(2)
        self.txtDetails.setObjectName(_fromUtf8("txtDetails"))
        self.txtSteps = QtGui.QTextEdit(self.frameDetails)
        self.txtSteps.setGeometry(QtCore.QRect(130, 190, 411, 141))
        self.txtSteps.setLineWidth(2)
        self.txtSteps.setObjectName(_fromUtf8("txtSteps"))
        self.frameTitlePage3 = QtGui.QFrame(self.page3)
        self.frameTitlePage3.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage3.setStyleSheet(_fromUtf8("#frameTitlePage3{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage3.setObjectName(_fromUtf8("frameTitlePage3"))
        self.lblTitlePage3 = QtGui.QLabel(self.frameTitlePage3)
        self.lblTitlePage3.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePage3.setFont(font)
        self.lblTitlePage3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePage3.setWordWrap(True)
        self.lblTitlePage3.setObjectName(_fromUtf8("lblTitlePage3"))
        self.btnBackPage3 = QtGui.QPushButton(self.page3)
        self.btnBackPage3.setGeometry(QtCore.QRect(430, 440, 68, 31))
        self.btnBackPage3.setObjectName(_fromUtf8("btnBackPage3"))
        self.btnNextPage3 = QtGui.QPushButton(self.page3)
        self.btnNextPage3.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnNextPage3.setObjectName(_fromUtf8("btnNextPage3"))
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtGui.QWidget()
        self.page4.setObjectName(_fromUtf8("page4"))
        self.frameDetailsPage4 = QtGui.QFrame(self.page4)
        self.frameDetailsPage4.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameDetailsPage4.setStyleSheet(_fromUtf8("#frameDetailsPage4{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameDetailsPage4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDetailsPage4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDetailsPage4.setObjectName(_fromUtf8("frameDetailsPage4"))
        self.gridLayout = QtGui.QGridLayout(self.frameDetailsPage4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.frameDetailsPage4)
        self.treeWidget.setLineWidth(2)
        self.treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_Arc = QtGui.QTreeWidgetItem(self.treeWidget)
        item_OS = QtGui.QTreeWidgetItem(item_Arc)
        item_Platform = QtGui.QTreeWidgetItem(item_Arc)
        item_UserData = QtGui.QTreeWidgetItem(self.treeWidget)
        item_ProblemType = QtGui.QTreeWidgetItem(item_UserData)
        item_Summary = QtGui.QTreeWidgetItem(item_UserData)
        item_Description = QtGui.QTreeWidgetItem(item_UserData)
        item_SysData = QtGui.QTreeWidgetItem(self.treeWidget)
        item_Commands = QtGui.QTreeWidgetItem(item_SysData)
        item_LogFiles = QtGui.QTreeWidgetItem(item_SysData)
        self.treeWidget.header().setDefaultSectionSize(200)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.btnBackPage4 = QtGui.QPushButton(self.page4)
        self.btnBackPage4.setGeometry(QtCore.QRect(430, 440, 68, 31))
        self.btnBackPage4.setObjectName(_fromUtf8("btnBackPage4"))
        self.btnSendPage4 = QtGui.QPushButton(self.page4)
        self.btnSendPage4.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnSendPage4.setObjectName(_fromUtf8("btnSendPage4"))
        self.frameTitlePage4 = QtGui.QFrame(self.page4)
        self.frameTitlePage4.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage4.setStyleSheet(_fromUtf8("#frameTitlePage4{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage4.setObjectName(_fromUtf8("frameTitlePage4"))
        self.lblTitlePage4 = QtGui.QLabel(self.frameTitlePage4)
        self.lblTitlePage4.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePage4.setFont(font)
        self.lblTitlePage4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePage4.setWordWrap(True)
        self.lblTitlePage4.setObjectName(_fromUtf8("lblTitlePage4"))
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtGui.QWidget()
        self.page5.setObjectName(_fromUtf8("page5"))
        self.frameTitlePage5 = QtGui.QFrame(self.page5)
        self.frameTitlePage5.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage5.setStyleSheet(_fromUtf8("#frameTitlePage5{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage5.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage5.setObjectName(_fromUtf8("frameTitlePage5"))
        self.lblTitlePage5 = QtGui.QLabel(self.frameTitlePage5)
        self.lblTitlePage5.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePage5.setFont(font)
        self.lblTitlePage5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePage5.setWordWrap(True)
        self.lblTitlePage5.setObjectName(_fromUtf8("lblTitlePage5"))
        self.frameResultPage5 = QtGui.QFrame(self.page5)
        self.frameResultPage5.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameResultPage5.setStyleSheet(_fromUtf8("#frameResultPage5{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameResultPage5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameResultPage5.setFrameShadow(QtGui.QFrame.Raised)
        self.frameResultPage5.setObjectName(_fromUtf8("frameResultPage5"))
        self.label = QtGui.QLabel(self.frameResultPage5)
        self.label.setGeometry(QtCore.QRect(20, 30, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frameResultPage5)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 131, 16))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frameResultPage5)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 341, 16))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frameResultPage5)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frameResultPage5)
        self.label_5.setGeometry(QtCore.QRect(190, 130, 351, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btnQuitPage5 = QtGui.QPushButton(self.page5)
        self.btnQuitPage5.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnQuitPage5.setObjectName(_fromUtf8("btnQuitPage5"))
        self.stackedWidget.addWidget(self.page5)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.frameTitlePage6 = QtGui.QFrame(self.page)
        self.frameTitlePage6.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.frameTitlePage6.setStyleSheet(_fromUtf8("#frameTitlePage6{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameTitlePage6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTitlePage6.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTitlePage6.setObjectName(_fromUtf8("frameTitlePage6"))
        self.lblTitlePage5_2 = QtGui.QLabel(self.frameTitlePage6)
        self.lblTitlePage5_2.setGeometry(QtCore.QRect(50, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTitlePage5_2.setFont(font)
        self.lblTitlePage5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitlePage5_2.setWordWrap(True)
        self.lblTitlePage5_2.setObjectName(_fromUtf8("lblTitlePage5_2"))
        self.frameResultPage6 = QtGui.QFrame(self.page)
        self.frameResultPage6.setGeometry(QtCore.QRect(10, 70, 561, 361))
        self.frameResultPage6.setStyleSheet(_fromUtf8("#frameResultPage6{\n"
"border: 3px solid gray;\n"
"border-radius: 10px;\n"
"}"))
        self.frameResultPage6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameResultPage6.setFrameShadow(QtGui.QFrame.Raised)
        self.frameResultPage6.setObjectName(_fromUtf8("frameResultPage6"))
        self.label_6 = QtGui.QLabel(self.frameResultPage6)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frameResultPage6)
        self.label_7.setGeometry(QtCore.QRect(20, 120, 131, 16))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.frameResultPage6)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 131, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.txtMail = QtGui.QTextEdit(self.frameResultPage6)
        self.txtMail.setGeometry(QtCore.QRect(150, 110, 251, 31))
        self.txtMail.setObjectName(_fromUtf8("txtMail"))
        self.txtPassword = QtGui.QTextEdit(self.frameResultPage6)
        self.txtPassword.setGeometry(QtCore.QRect(150, 150, 251, 31))
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.btnLogin = QtGui.QPushButton(self.frameResultPage6)
        self.btnLogin.setGeometry(QtCore.QRect(300, 200, 99, 31))
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.btnQuitPage6 = QtGui.QPushButton(self.page)
        self.btnQuitPage6.setGeometry(QtCore.QRect(500, 440, 71, 31))
        self.btnQuitPage6.setObjectName(_fromUtf8("btnQuitPage6"))
        self.btnBackPage6 = QtGui.QPushButton(self.page)
        self.btnBackPage6.setGeometry(QtCore.QRect(420, 440, 71, 31))
        self.btnBackPage6.setObjectName(_fromUtf8("btnBackPage6"))
        self.stackedWidget.addWidget(self.page)
        BugReporter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BugReporter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        BugReporter.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BugReporter)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BugReporter.setStatusBar(self.statusbar)

        self.retranslateUi(BugReporter)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BugReporter)




    def retranslateUi(self, BugReporter):
        BugReporter.setWindowTitle(QtGui.QApplication.translate("BugReporter", "Bug Reporter", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePae1.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.lblquestionPage1.setText(QtGui.QApplication.translate("BugReporter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Wellcome to Pardus Bug Reporting Tool. This tool allows you to enter bugs that you have encountered in your Pardus system.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNextPage1.setText(QtGui.QApplication.translate("BugReporter", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancelPage1.setText(QtGui.QApplication.translate("BugReporter", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePage2.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDisplay.setText(QtGui.QApplication.translate("BugReporter", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.lblquestion.setText(QtGui.QApplication.translate("BugReporter", "Select the type of the problem you have encountered. ", None, QtGui.QApplication.UnicodeUTF8))
        self.rbStorage.setText(QtGui.QApplication.translate("BugReporter", "Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSoundAudio.setText(QtGui.QApplication.translate("BugReporter", "Sound / Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOthers.setText(QtGui.QApplication.translate("BugReporter", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackPage2.setText(QtGui.QApplication.translate("BugReporter", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNextPage2.setText(QtGui.QApplication.translate("BugReporter", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSteps.setText(QtGui.QApplication.translate("BugReporter", "Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSummary.setToolTip(QtGui.QApplication.translate("BugReporter", "A short summary that describes the bug you have entered...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSummary.setText(QtGui.QApplication.translate("BugReporter", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDetails.setText(QtGui.QApplication.translate("BugReporter", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.txtDetails.setToolTip(QtGui.QApplication.translate("BugReporter", "Detailed description of the bug you have encountered...", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSteps.setToolTip(QtGui.QApplication.translate("BugReporter", "Steps that explains how you have encountered the bug. Please make sure that you entered all necessary steps one by one to help devolopers fix the problem...", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSteps.setHtml(QtGui.QApplication.translate("BugReporter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePage3.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackPage3.setText(QtGui.QApplication.translate("BugReporter", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNextPage3.setText(QtGui.QApplication.translate("BugReporter", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("BugReporter", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("BugReporter", "Data", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("BugReporter", "Architecture", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("BugReporter", "OS", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("BugReporter", "Kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("BugReporter", "User Data", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("BugReporter", "Problem Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("BugReporter", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).setText(0, QtGui.QApplication.translate("BugReporter", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("BugReporter", "System Data", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.btnBackPage4.setText(QtGui.QApplication.translate("BugReporter", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSendPage4.setText(QtGui.QApplication.translate("BugReporter", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePage4.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePage5.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BugReporter", "Your bug details has been sent to Pardus devolopers. Bug details are as following", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BugReporter", "Bug ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BugReporter", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BugReporter", "Link to Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BugReporter", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuitPage5.setText(QtGui.QApplication.translate("BugReporter", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitlePage5_2.setText(QtGui.QApplication.translate("BugReporter", "Pardus Bug Reporting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BugReporter", "You need to log in to send this bug entry. Please login to bugzilla by using your e-mail and password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BugReporter", "E-Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BugReporter", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogin.setText(QtGui.QApplication.translate("BugReporter", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuitPage6.setText(QtGui.QApplication.translate("BugReporter", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackPage6.setText(QtGui.QApplication.translate("BugReporter", "Back", None, QtGui.QApplication.UnicodeUTF8))



