#!/bin/sh -l

if grep "livecd" /proc/cmdline \
    || grep "livedisk" /proc/cmdline \
    || test -e /etc/yali-is-firstboot; then

    HOME=/root
    USER=root
    export HOME USER

    exec /usr/bin/xinit /usr/bin/yali4-bin -- vt7 -nolisten tcp -br
fi
