<?php

    // TUBITAK/UEAKE - 2006-07 - Pardus
    // Gökmen GÖKSEL <gokmen@pardus.org.tr>
    // Config file for PardusWeb
    // Edit and saveas 'config.php' in the same directory

    $CF["DbHost"]  = 'localhost';
    $CF["DbUser"]  = 'username';
    $CF["DbPass"]  = 'password';
    $CF["DbData"]  = 'dbname';
    $CF["DbLogLevel"] = 4;
    $CF["UsePrefix"] =  false;

    $BlogRssLink = "http://*";
    $PageTitle = "Pardus";

?>
