#include "helper.h"
#include <iostream>
#include <QStringList>
#include <QFile>
#include <QTextStream>
#include <QDebug>

ActionReply Helper::createReply(int code, const QVariantMap *returnData)
{
    ActionReply reply;

    if (code) {
        reply = ActionReply::HelperError;
        reply.setErrorCode(code);
    } else {
        reply = ActionReply::SuccessReply;
    }

    if (returnData)
        reply.setData(*returnData);

    return reply;
}


bool Helper::writeLocale(const QString &locale)
{
    qDebug() << locale << endl;;
    /*QString xorgFile = "/etc/X11/xorg.conf.d/00-configured-keymap.conf";

    QString xorgContent;
    xorgContent =   "# This file is generated by KCM Keyboard Module.\n"
                    "# If you want to change settings in this file, edit\n"
                    "# the file 10-keyboard.conf in the same directory.\n\n"
                    "Section \"InputClass\"\n"
                    "       Identifier\t\"Configured Keymap\"\n"
                    "       MatchisKeyboard\t\"on\"\n"
                    "       MatchTag\t\"use_configured_keymap\"\n\n"
                    "EndSection\n";

    // open file to write
    QFile file(xorgFile);
    if( !file.open( QIODevice::WriteOnly | QIODevice::Text)) {
        qDebug() << "Failed to write.";
        return false;
    }

    // content of fields is saved to the new file
    QTextStream out(&file);
    out << xorgContent;
    file.close();*/

    return true;
}

ActionReply Helper::managelocale(QVariantMap args)
{
    int code = 0;

    QString locale = args.value("locale").toString();

    qDebug() << locale << endl;

    code = (writeLocale(locale) ? 0 : WriteLocaleError);
    return ActionReply::SuccessReply;
}

KDE4_AUTH_HELPER_MAIN("org.kde.kcontrol.kcmlocale", Helper)
