# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Jul 29 19:43:01 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(798, 573)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 301))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.statusLabel = QtGui.QLabel(self.frame)
        self.statusLabel.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.statusLabel.setObjectName("statusLabel")
        self.backupList = KListWidget(self.frame)
        self.backupList.setGeometry(QtCore.QRect(10, 30, 521, 261))
        self.backupList.setObjectName("backupList")
        self.kbuttongroup = KButtonGroup(self.frame)
        self.kbuttongroup.setGeometry(QtCore.QRect(540, 30, 231, 251))
        self.kbuttongroup.setObjectName("kbuttongroup")
        self.archiveButton = KPushButton(self.kbuttongroup)
        self.archiveButton.setGeometry(QtCore.QRect(50, 90, 141, 31))
        self.archiveButton.setObjectName("archiveButton")
        self.restoreButton = KPushButton(self.kbuttongroup)
        self.restoreButton.setGeometry(QtCore.QRect(50, 50, 141, 31))
        self.restoreButton.setObjectName("restoreButton")
        self.importButton = KPushButton(self.kbuttongroup)
        self.importButton.setGeometry(QtCore.QRect(50, 130, 141, 31))
        self.importButton.setObjectName("importButton")
        self.backupNow = KPushButton(self.kbuttongroup)
        self.backupNow.setGeometry(QtCore.QRect(50, 170, 141, 31))
        self.backupNow.setObjectName("backupNow")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 320, 781, 221))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.backupLog = KTextBrowser(self.frame_2)
        self.backupLog.setGeometry(QtCore.QRect(10, 30, 761, 181))
        self.backupLog.setObjectName("backupLog")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionBackup_Now = QtGui.QAction(MainWindow)
        self.actionBackup_Now.setObjectName("actionBackup_Now")
        self.actionTag_Selected_Backup = QtGui.QAction(MainWindow)
        self.actionTag_Selected_Backup.setObjectName("actionTag_Selected_Backup")
        self.actionArchive_Selected_Backup = QtGui.QAction(MainWindow)
        self.actionArchive_Selected_Backup.setObjectName("actionArchive_Selected_Backup")
        self.actionRestore_Selected_Backup = QtGui.QAction(MainWindow)
        self.actionRestore_Selected_Backup.setObjectName("actionRestore_Selected_Backup")
        self.actionInitialize = QtGui.QAction(MainWindow)
        self.actionInitialize.setObjectName("actionInitialize")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_KDE = QtGui.QAction(MainWindow)
        self.actionAbout_KDE.setObjectName("actionAbout_KDE")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "KonfigTracker - KDE Configuration Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "KonfigTracker Database Status", None, QtGui.QApplication.UnicodeUTF8))
        self.archiveButton.setText(QtGui.QApplication.translate("MainWindow", "Export configurations", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("MainWindow", "Import configurations", None, QtGui.QApplication.UnicodeUTF8))
        self.backupNow.setText(QtGui.QApplication.translate("MainWindow", "Backup Now", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Backup Information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup_Now.setText(QtGui.QApplication.translate("MainWindow", "Backup Now", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTag_Selected_Backup.setText(QtGui.QApplication.translate("MainWindow", "Tag Selected Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchive_Selected_Backup.setText(QtGui.QApplication.translate("MainWindow", "Archive Selected Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore_Selected_Backup.setText(QtGui.QApplication.translate("MainWindow", "Selected Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInitialize.setText(QtGui.QApplication.translate("MainWindow", "Initialize ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_KDE.setText(QtGui.QApplication.translate("MainWindow", "About KDE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from PyKDE4.kdeui import KButtonGroup, KPushButton, KListWidget, KTextBrowser
