# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quickformat.ui'
#
# Created: Thu Jul  7 16:28:27 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QuickFormat(object):
    def setupUi(self, QuickFormat):
        QuickFormat.setObjectName(_fromUtf8("QuickFormat"))
        QuickFormat.resize(420, 227)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuickFormat.sizePolicy().hasHeightForWidth())
        QuickFormat.setSizePolicy(sizePolicy)
        QuickFormat.setMinimumSize(QtCore.QSize(420, 227))
        QuickFormat.setMaximumSize(QtCore.QSize(420, 227))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/draw-eraser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuickFormat.setWindowIcon(icon)
        QuickFormat.setStyleSheet(_fromUtf8(""))
        self.gridLayout_3 = QtGui.QGridLayout(QuickFormat)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.line_3 = QtGui.QFrame(QuickFormat)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(4, 4, 6, 6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_format = QtGui.QPushButton(QuickFormat)
        self.btn_format.setIcon(icon)
        self.btn_format.setObjectName(_fromUtf8("btn_format"))
        self.horizontalLayout.addWidget(self.btn_format)
        self.btn_cancel = QtGui.QPushButton(QuickFormat)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dialog-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.grpNonArgs = QtGui.QFrame(QuickFormat)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.grpNonArgs.setFont(font)
        self.grpNonArgs.setObjectName(_fromUtf8("grpNonArgs"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpNonArgs)
        self.gridLayout_2.setContentsMargins(16, 8, 10, 8)
        self.gridLayout_2.setHorizontalSpacing(16)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.icon = QtGui.QLabel(self.grpNonArgs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(128)
        sizePolicy.setVerticalStretch(128)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMinimumSize(QtCore.QSize(128, 128))
        self.icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.icon.setStyleSheet(_fromUtf8(""))
        self.icon.setText(_fromUtf8(""))
        self.icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/drive-removable-media-usb.png")))
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName(_fromUtf8("icon"))
        self.gridLayout_2.addWidget(self.icon, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.grpNonArgs)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.volumeLabel = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeLabel.sizePolicy().hasHeightForWidth())
        self.volumeLabel.setSizePolicy(sizePolicy)
        self.volumeLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.volumeLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeLabel.setFont(font)
        self.volumeLabel.setObjectName(_fromUtf8("volumeLabel"))
        self.gridLayout.addWidget(self.volumeLabel, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.fileSystem = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSystem.sizePolicy().hasHeightForWidth())
        self.fileSystem.setSizePolicy(sizePolicy)
        self.fileSystem.setMinimumSize(QtCore.QSize(113, 30))
        self.fileSystem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.fileSystem.setFont(font)
        self.fileSystem.setObjectName(_fromUtf8("fileSystem"))
        self.gridLayout.addWidget(self.fileSystem, 3, 1, 1, 1)
        self.volumeName = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeName.sizePolicy().hasHeightForWidth())
        self.volumeName.setSizePolicy(sizePolicy)
        self.volumeName.setMinimumSize(QtCore.QSize(113, 30))
        self.volumeName.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeName.setFont(font)
        self.volumeName.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.volumeName.setMinimumContentsLength(0)
        self.volumeName.setIconSize(QtCore.QSize(32, 32))
        self.volumeName.setFrame(True)
        self.volumeName.setModelColumn(0)
        self.volumeName.setObjectName(_fromUtf8("volumeName"))
        self.gridLayout.addWidget(self.volumeName, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.grpNonArgs, 0, 0, 1, 1)

        self.retranslateUi(QuickFormat)
        QtCore.QMetaObject.connectSlotsByName(QuickFormat)

    def retranslateUi(self, QuickFormat):
        QuickFormat.setWindowTitle(QtGui.QApplication.translate("QuickFormat", "Quick Format", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_format.setText(QtGui.QApplication.translate("QuickFormat", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("QuickFormat", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QuickFormat", "Volume Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QuickFormat", "File System", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QuickFormat", "Volume Label", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
